# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 328bb1698f795e2644c6ce3c99c8371f6f4d4da1bee50bdf74df46ddd2637850a147119617806fda479d25c790300d40011f5a1b17d5244bcd62875cfc4418d3

test:
  secret_key_base: 47c734d47ee0158052a72ef44165756937fdce64e842081be14ee1bc7594faf3c689ff45734744ac52e5527b2217e738681165a6079b761b54903691570f9d26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
